### ISSUE TITLE
购物车用户体验

### ISSUE THREAD

**Issue by muiccc** [youzan/vant-demo#1]
全选按钮, 左右滑动删除, 单品 数量更改

**Comment by chenjiahan** [comment]
后续会继续丰富购物车示例

**Comment by lanyanguang32** [comment]
搞个完整的电商demo呗。。。这样上手快。。。现在电商应用满大街都是了，也不是什么秘密。但对于一套想要推广的UI 来说，完整的应用案例会吸引更多的人使用。技术的开源推广目的也与此。

**Comment by chenjiahan** [comment]
@lanyanguang32 
Demo 的主要目的是提供一个用法的示例，不适合太过复杂。
且提供完整的电商 Demo 目前不是我们工作的重心，如果有兴趣欢迎帮助我们完善这个仓库

**Comment by 444194401** [comment]
弄个登录页面。

**Comment by abc18583757301** [comment]
大佬  下载下来  没有package.json啊？怎么npm install？

**Comment by chenjiahan** [comment]
@abc18583757301 在各个目录下 install

**Comment by chenjiahan** [comment]
暂时不计划继续扩充购物车示例了，这个仓库更倾向于提供各种工程的配置示例
