### ISSUE TITLE
build后dist文件夹下没有index文件

### ISSUE THREAD

**Issue by jacky3731** [youzan/vant-demo#15]
在本地可以跑起来，但build后dist文件夹下没有index文件，程序无法启动。
dist文件夹下只有css\js文件夹

**Comment by waittingbar** [comment]
修改这个文件 ..\config\index.js 

`env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: './',`

**Comment by chenjiahan** [comment]
@waittingbar 可以帮忙提个 PR 喔

**Comment by waittingbar** [comment]
@chenjiahan 好的，我试下

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant-demo/pull/16
