### ISSUE TITLE
能否增加typescript配置demo？谢谢！

### ISSUE THREAD

**Issue by qidaneix** [youzan/vant-demo#19]
最好能有 ts-import-plugin 按需加载的示例

**Comment by chenmf6** [comment]
同求！

**Comment by chenmf6** [comment]
采用vue-cli3 + typescript + ts-import-plugin的技术栈，
在组件里面用import {Dialog} from 'vant'的方式来引入组件，
结果编译报错了：找不到对应的css文件：
![image](https://user-images.githubusercontent.com/13809734/49568297-91ef5c00-f96b-11e8-9a7b-6e2b17e5663c.png)

vue.config.js的配置如图：
![image](https://user-images.githubusercontent.com/13809734/49568339-b5b2a200-f96b-11e8-9f90-c55799fcdefd.png)


请问是否配置有误？能不能给一个ts的demo

**Comment by chenjiahan** [comment]
ts 示例已添加
