### ISSUE TITLE
购物车页面打开样式错乱

### ISSUE THREAD

**Issue by zyhui98** [youzan/vant-demo#20]
![qq 20181128093848](https://user-images.githubusercontent.com/5568889/49122963-b1461380-f2f1-11e8-9656-c3ec2641bdfd.png)

**Comment by bolechen** [comment]
+1

**Comment by zyhui98** [comment]
![image](https://user-images.githubusercontent.com/5568889/49268956-6bc64980-f49d-11e8-8813-550aabab070c.png)

**Comment by zyhui98** [comment]
可以了

**Comment by chenjiahan** [comment]
感谢反馈，这个是 vant 中的样式变更导致的，已经更新示例代码，后续会在 vant 中修复

**Comment by Farb** [comment]
![image](https://user-images.githubusercontent.com/7587900/70860662-63816500-1f5f-11ea-8720-db2714519750.png)
我这边样式也错乱了，vant 版本 "vant": "^2.3.0-beta.4",
之前1.x版本的时候还好好的

**Comment by Farb** [comment]
@chenjiahan
