### ISSUE TITLE
pc端微信兼容问题

### ISSUE THREAD

**Issue by longjining** [youzan/vant-demo#28]
使用微信web开发者工具打开demo，但是点击的事件无法触发，或者是点击区域发生偏离，如点击的是p(10,20)，但是响应的是另一个位置p(20,50)的按钮，
这样就导致 pc端微信无法正常使用，请问一下这个问题能修复吗？

**Comment by chenjiahan** [comment]
应该是微信开发者工具的问题，没法修复
