### ISSUE TITLE
npm run serve 问题

### ISSUE THREAD

**Issue by guhongyeying** [youzan/vant-demo#32]
npm ERR! path E:\git\github\vant-demo\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'E:\git\github\vant-demo\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-02-14T10_44_57_930Z-debug.log

**Comment by guhongyeying** [comment]
项目缺少文件把！package.json等

**Comment by Madq92** [comment]
> 项目缺少文件把！package.json等
cd base

**Comment by chenjiahan** [comment]
在子目录下
