### ISSUE TITLE
你好，这边有个小建议

### ISSUE THREAD

**Issue by AK47-dadada** [youzan/vant-demo#35]
可以把vw的配置demo也放到里面去吗？我已经配置了vw的适配，但是还是希望有个官方的vw配置方案，谢谢。

**Comment by chenjiahan** [comment]
后续会加上对应的示例

**Comment by liushiyueyueniao** [comment]
这种电商类的app 怎么能少了vuex呢  @chenjiahan

**Comment by chenjiahan** [comment]
@liushiyueyueniao 目前的 demo 主要都是为了演示 Vant 相关的一些配置，Vuex 的话看官方文档就好啦

**Comment by zhuxiwen** [comment]
postcss-px-to-viewport
这个不错，我用的也是vw

**Comment by chenjiahan** [comment]
vw 示例加上了
