### ISSUE TITLE
rem的字体大小问题

### ISSUE THREAD

**Issue by dianjie** [youzan/vant-demo#39]
demo里rem通过引入`amfe-flexible`
动态设置`html`、`body`的字体大小
`index.html`将`viewport`为
 `<meta name="viewport" content="width=device-width,initial-scale=1.0">`
当在页面添加
`<p>测试</p>`
`<div>测试</div>`
等标签时，会出现pc端字体很小，手机端字体很大的问题，因为他们的`font-size`继承于`body`

我的解决方案是：
1、删除`amfe-flexible`的引入
2、删除`index.html`的 `<meta name="viewport" content="width=device-width,initial-scale=1.0">`
3、引入[ant-design-mobile](https://github.com/ant-design/ant-design-mobile/wiki/HD) 高清方案的` antm-viewport.min.js`

**Comment by chenjiahan** [comment]
这个问题很简单呐，你在 body 上设置默认字体大小就好，比如 16px
