### ISSUE TITLE
ts自定义主题 引入主题文件报错

### ISSUE THREAD

**Issue by JustGogoing** [youzan/vant-demo#42]
这样写可以正确修改主题
`
less: {
        modifyVars: {
          red: '#ccc',
          blue: '#3eaf7c',
          orange: '#f08d49',
          'text-color': '#111'
        }
      }
`
但是
`
less: {
        modifyVars: {
          // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
          'hack': `true; @import "src/assets/css/theme.less";`
        }
      }`

这样就报错
![image](https://user-images.githubusercontent.com/17309976/64165468-c0a54f00-ce77-11e9-903f-befd57d13370.png)

**Comment by chenjiahan** [comment]
上面注释里写的蛮清楚了，文件路径为绝对路径，你要用 path 模块拼接一下路径
