### ISSUE TITLE
已勾选npm选项但是还是出现Component is not found in path "@vant/weapp/dist/image/index" 错误

### ISSUE THREAD

**Issue by dennis-ji** [youzan/vant-demo#58]
```shell
jsEnginScriptError
Component is not found in path "@vant/weapp/dist/image/index" (using by "pages/goods/index");onAppRoute
Error: Component is not found in path "@vant/weapp/dist/image/index" (using by "pages/goods/index")
    at G (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1501083)
    at G (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1501287)
    at http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1522327
    at Module.We (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1522906)
    at Function.value (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1607887)
    at Tt (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1623908)
    at http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1628170
    at xt (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1628663)
    at Function.<anonymous> (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1632248)
    at i.<anonymous> (http://127.0.0.1:62977/appservice/__dev__/WAService.js:2:1600839)
console.error @ VM174:1
errorReport @ VM180 WAService.js:2
(anonymous) @ VM180 WAService.js:2
E @ VM180 WAService.js:2
(anonymous) @ VM180 WAService.js:2
i.emit @ VM180 WAService.js:2
emit @ VM180 WAService.js:2
(anonymous) @ VM180 WAService.js:2
(anonymous) @ VM180 WAService.js:2
n @ VM178 asdebug.js:1
(anonymous) @ VM178 asdebug.js:1
(anonymous) @ VM178 asdebug.js:1
_ws.onmessage @ VM178 asdebug.js:1
```

**Comment by henan715** [comment]
我也遇到了这个问题，原因是启用了NPM之后，没有构建而导致的，解决方法是：点击工具--点击构建NPM，构建成功后，在小程序的根目录下，会出现一个miniprogram_npm目录，此时再刷新页面就可以成功预览组件了。

**Comment by guzhao593** [comment]
![image](https://user-images.githubusercontent.com/30461881/72613395-572b6600-396a-11ea-82ea-f6c2e0834539.png)
我这里是因为下载下来的npm包的路径少了dist

**Comment by rcl4444** [comment]
环境
微信开发者工具 Stable v1.02.1911180
node v12.0
npm 6.10.3
描述
包路径
![image](https://user-images.githubusercontent.com/19640490/75778748-583a1a80-5d93-11ea-8184-d82974b936f7.png)
![image](https://user-images.githubusercontent.com/19640490/75778827-7acc3380-5d93-11ea-98c2-7bd935b24974.png)
结论
貌似是微信开发工具的npm构建的目录有问题

**Comment by CostinYuan** [comment]
> 我也遇到了这个问题，原因是启用了NPM之后，没有构建而导致的，解决方法是：点击工具--点击构建NPM，构建成功后，在小程序的根目录下，会出现一个miniprogram_npm目录，此时再刷新页面就可以成功预览组件了。

重新构建还是不行。。

**Comment by jiaxin11** [comment]
修改一下pages/goods/index.json 将dist/全部替换为""就能找到了

**Comment by Sirlanri** [comment]
> 修改一下pages/goods/index.json 将dist/全部替换为""就能找到了

采用你的方案解决了，是路径的问题。
用小程序的两行npm命令，安装vant，nimiprogram_npm目录内的vant文件夹不包含dist目录。

### 解决方案有两种：
1：如 @dennis-ji  所说，使用的时候不要引用dist路径。
2：在GitHub下载官方源码 https://github.com/youzan/vant-weapp/archive/master.zip
把dist目录复制到 nimiprogram_npm/@vant/weapp

**Comment by Ku-M** [comment]
我手动把 dist/删除了 23333

**Comment by shuperry** [comment]
开发者工具里有个【使用新的编译模块】，不勾选这个，再把代码 json 文件里的 "dist/" 给替换成空字符串，这样就可以了
