### ISSUE TITLE
这是什么样式？

### ISSUE THREAD

**Issue by lly835** [youzan/vant-demo#63]
文档里没找到
![Jietu20200423-010508](https://user-images.githubusercontent.com/2225913/80012325-bb2c7000-84ff-11ea-8ba0-78df8ea353c8.jpg)
![Jietu20200423-010946@2x](https://user-images.githubusercontent.com/2225913/80012331-bebff700-84ff-11ea-877c-84a109ef7472.jpg)

**Comment by chenjiahan** [comment]
这是文档示例，不属于组件提供的样式

**Comment by lly835** [comment]
这个样式挺好看的，可以写到组件里去

**Comment by chenjiahan** [comment]
木有计划呢
