### ISSUE TITLE
don't know how to turn this value into a node

### ISSUE THREAD

**Issue by luocong2016** [youzan/vant-demo#65]
报错
$ vant-cli test
 FAIL  src/my-button/test/index.spec.js
  ● Test suite failed to run
  D:\demo\components-vue\src\my-button\index.vue: don't know how to turn this value into a node
环境
win7 nodeV12.16.3 npmV6.13.4  sass

**Comment by chenjiahan** [comment]
问题与本仓库无关，建议自行搜索问题原因
