### ISSUE TITLE
vant-cli build后的lib，vue-cli构建的项目引用lib中的组件，vue-cli build后的vendors.js会包含两份vue代码。

### ISSUE THREAD

**Issue by nanchengjiumeng** [youzan/vant-demo#66]
vue-cli构建项目后，通过yarn link方式引用的vant-cli项目。
如果vant-cli项目中node_modules目录下没有vue依赖，不会发生这种现象。

**Comment by chenjiahan** [comment]
可以使用 webpack 的 symlinks 配置来调整 link 模块的 require 规则

https://webpack.js.org/configuration/resolve/#resolvesymlinks
