### ISSUE TITLE
fix merge is not a function 

### ISSUE THREAD

**Issue by LanjianNUll** [youzan/vant-demo#70]
fix merge is not a function 

"webpack-merge": "^5.1.1"

vant-demo/vant/typescript/vue.config.js 
const merge = require('webpack-merge');  => const {merge} = require('webpack-merge');

**Comment by longletian** [comment]
我也遇到了这个问题 你的解决了吗  好像和.babelrc有关系

**Comment by longletian** [comment]
你需要把这个包 删掉 "webpack-merge" 
![image](https://user-images.githubusercontent.com/28197668/90272098-730ad200-de8f-11ea-8521-3ae1172408e7.png)
这个默认是在ts中的 你再引入一个就会冲突 我也是遇到了 刚好解决掉

**Comment by xiaoai7904** [comment]
const { merge } = require('webpack-merge');

**Comment by longletian** [comment]
我之前试了 不是这个问题，我是因为我自己又重新npm  install  webpack-merge

**Comment by xiaoai7904** [comment]
如果不重新安装,在vue.config.js直接使用会报错呢
你怎么用的？

**Comment by chenjiahan** [comment]
webpack-merge 不同版本的用法有些许差别，跟 demo 本身关系不大
