### ISSUE TITLE
微信小程序demo示例无法运行

### ISSUE THREAD

**Issue by beiketianzhuang** [youzan/vant-demo#75]
Hi,我刚下载了微信小程序的demo的应用，然后进入base目录，并运行了npm install
然后运行npm run dev报错
`npm ERR! missing script: dev npm ERR! A complete log of this run can be found in:`

**Comment by beiketianzhuang** [comment]
@Lindysen 可以帮忙看看嘛什么原因
这是具体的报错信息：

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\soft\\node\\node.exe',
1 verbose cli   'D:\\soft\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose stack Error: missing script: dev
4 verbose stack     at run (D:\soft\node\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at D:\soft\node\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at D:\soft\node\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at D:\soft\node\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (D:\soft\node\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (D:\soft\node\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (D:\soft\node\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at ReadFileContext.<anonymous> (D:\soft\node\node_modules\npm\node_modules\read-package-json\read-json.js:350:20)
4 verbose stack     at ReadFileContext.callback (D:\soft\node\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16)
4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
5 verbose cwd D:\qzw\vant-demo\vant-weapp\base
6 verbose Windows_NT 10.0.18363
7 verbose argv "D:\\soft\\node\\node.exe" "D:\\soft\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 verbose node v12.18.3
9 verbose npm  v6.14.6
10 error missing script: dev
11 verbose exit [ 1, true ]

**Comment by han837951112** [comment]
> Hi,我刚下载了微信小程序的demo的应用，然后进入base目录，并运行了npm install
> 然后运行npm run dev报错
> `npm ERR! missing script: dev npm ERR! A complete log of this run can be found in:`

install 之后不用 run， 看一下微信的npm支持文档
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
