### ISSUE TITLE
vant weapp 中的transtion组件引入了， 但是却用不了  ， 包裹的元素在控制台里查看既然消失了， 没有了

### ISSUE THREAD

**Issue by ldl97729** [youzan/vant-demo#77]
vant weapp 中的transtion组件引入了， 但是却用不了  ， 包裹的元素在控制台里查看既然消失了， 没有了

**Comment by chenjiahan** [comment]
请到 vant-weapp 仓库下按照 issue 模板进行反馈，感谢配合
