### ISSUE TITLE
新搭建的vue cli3项目引入vant报错

### ISSUE THREAD

**Issue by 15257174804** [youzan/vant-demo#78]
搭建完vue cli3项目，按照vant文档下载了vant 和babel-plugin-import
下载命令行：
npm i vant@next -S
npm i babel-plugin-import -的
<img width="772" alt="packjson" src="https://user-images.githubusercontent.com/58280930/101751890-cd4d3400-3b0b-11eb-9e4f-5ee45558c3d8.png">

在babel.config.js里配置如下：
<img width="647" alt="babel" src="https://user-images.githubusercontent.com/58280930/101751326-1c469980-3b0b-11eb-850f-0a10157699b8.png">

在main.js中引入:
<img width="937" alt="main" src="https://user-images.githubusercontent.com/58280930/101751468-439d6680-3b0b-11eb-8813-fa4d3fef3125.png">

在jysearch.vue中使用：
<img width="665" alt="vue" src="https://user-images.githubusercontent.com/58280930/101751603-6a5b9d00-3b0b-11eb-832e-8cde1170d811.png">

npm run serve运行之后报错如下：
![error](https://user-images.githubusercontent.com/58280930/101751755-9b3bd200-3b0b-11eb-8ecd-3abb1621acf1.png)

在网上百度了好多办法一直无法解决，help！！！

**Comment by chenjiahan** [comment]
初始化的时候，请注意区分你使用的是 Vue 2 模板还是 Vue 3 模板，如果使用 Vue 2 模板，请安装 Vant 2.x 版本

```bash
yarn add vant@2
```
