### ISSUE TITLE
按需引入示例打包后中依然会引入业务组件：AddressEdit 地址编辑

### ISSUE THREAD

**Issue by paddylives** [youzan/vant-demo#81]
描述：
使用demo中的typescript（配置 typescript 按需引入）直接打包，从打包的代码中css引入是正常的按需引入（虽然会引入大量的iconfont）,但是在chunk-vendors.23ec0739.js中发现部分代码显示是地址编辑组件的，代码中并未用到，不知道为何会被打包进入（经查找其他使用vant项目都存在该问题），顺便问下如何不引入iconfont(业务中图片都是使用自己的png图片)
打包代码截图：
![image](https://user-images.githubusercontent.com/75835983/106843393-811c0b80-66d8-11eb-843d-2ae889baf419.png)

**Comment by junbinding** [comment]
我也发现了，难受。。

**Comment by chenjiahan** [comment]
这个是 i18n 文件，不是 AddressEdit 的源代码
