### ISSUE TITLE
适配iPhone X 等机型的配置要写在哪里。。。

### ISSUE THREAD

**Issue by xu-Aurora** [youzan/vant-demo#85]
`van-nav-bar safe-area-inset-top`

van-number-keyboard safe-area-inset-bottom 

这两个东西分别写在哪里？

>

**Comment by xu-Aurora** [comment]
<van-nav-bar safe-area-inset-top />


<van-number-keyboard safe-area-inset-bottom />

**Comment by xu-Aurora** [comment]
> 这两个东西分别写在哪里？

<van-nav-bar safe-area-inset-top />

<van-number-keyboard safe-area-inset-bottom />

**Comment by xu-Aurora** [comment]
<van-nav-bar safe-area-inset-top />


<van-number-keyboard safe-area-inset-bottom />

**Comment by chenjiahan** [comment]
写在组件标签的 props 上
