### ISSUE TITLE
关于vue3  <keep-alive> 无效问题

### ISSUE THREAD

**Issue by liguanfeng** [youzan/vant-demo#88]
Q: vue3 缓存页面无效 ，跳转之后返回 会刷新页面导致  input 输入框内容被清除
APP.vue 代码
<template>
    <div id="app">
        <keep-alive>
            <router-view/>
        </keep-alive>
    </div>
</template>

**Comment by chenjiahan** [comment]
这个问题与 demo 仓库无关
