### ISSUE TITLE
使用 Toast 轻提示组件svg图标找不到

### ISSUE THREAD

**Issue by toFrankie** [youzan/vant-demo#9]
成功提示和失败提示的success.svg、fail.svg找不到，报错信息如下图

<img width="1128" alt="jietu20180412-013726" src="https://user-images.githubusercontent.com/26947203/38633541-978aae38-3df2-11e8-8689-8f5c659c3fc5.png">

**Comment by chenjiahan** [comment]
与本项目无关的问题
