### ISSUE TITLE
使用vant-cli开发的组件库，在遇到vant按需加载和自定义主题时，cell和field组件样式相互影响

### ISSUE THREAD

**Issue by weiliangdexinqing** [youzan/vant-demo#91]
使用vant-cli开发的组件库A，使用了Cell组件；项目B使用了vant的组件field，并且按需引入、使用自定义主题色。
这时组件库A的cell组件样式和项目B的field组件样式相互影响，样式错乱。

**Comment by chenjiahan** [comment]
请到 vant 仓库下反馈问题。
