### ISSUE TITLE
cnd崩溃了。。

### ISSUE THREAD

**Issue by dongbs** [youzan/vant-demo#96]
cnd崩溃了。。

**Comment by dongbs** [comment]
cnd崩溃了。。

**Comment by dongbs** [comment]
cdn.jsdelivr.net崩溃了。。

**Comment by chenjiahan** [comment]
看起来是 jsdelivr 崩了，可以换其他 CDN 试试

![image](https://user-images.githubusercontent.com/7237365/146723160-836f2fdb-0bfb-4e4c-b77e-51e9d585af70.png)

**Comment by dongbs** [comment]
其他的比较慢，有直接线下的包文件嘛



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: neverland ***@***.***&gt;
发送时间: 2021年12月20日 14:42
收件人: youzan/vant-demo ***@***.***&gt;
抄送: dongbs ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[youzan/vant-demo] cnd崩溃了。。 (Issue #96)





 
看起来是 jsdelivr 崩了，可以换其他 CDN 试试
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenjiahan** [comment]
直接从其他 CDN 下载一份就可以

**Comment by dongbs** [comment]
***@***.***/dist/vue.min.js
***@***.***/lib/vant.min.js

***@***.***/lib/index.css
以上我之前引用的


以下是我之后引用的
https://cdnjs.cloudflare.com/ajax/libs/vant/2.12.37/index.css
***@***.***/dist/vue.min.js
https://cdnjs.cloudflare.com/ajax/libs/vant/2.12.37/vant.min.js


之后一些客户打开页面是空白。部分客户没问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-demo] cnd崩溃了。。 (Issue #96)





 
直接从其他 CDN 下载一份就可以
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongbs** [comment]
真狠奇怪，时好 时不好的.脑壳疼.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-demo] cnd崩溃了。。 (Issue #96)





 
直接从其他 CDN 下载一份就可以
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
